### ISSUE TITLE
Error occured

### ISSUE THREAD

**Issue by andrewshi910** [kaiiiz/AnkiCC#4]
an error is occured when trying to use the addon 
the problem occurs upon clicking AnkiCC in tool dropdown menu

Following is the debug info

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\ankicc\main.py", line 234, in main
    dialog = AnkiCCDialog(deck_names_and_ids)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\ankicc\main.py", line 84, in __init__
    self.ignored_flds.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
AttributeError: type object 'QAbstractItemView' has no attribute 'MultiSelection'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiCC ['ankicc', 0, 'None', '']

===IDs of active AnkiWeb add-ons===

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by AC9292** [comment]
Same

**Comment by kaiiiz** [comment]
Fixed in v0.3.0 , the latest update has already been deployed to Anki Web.
